server.port=8090

#Configuring application datasource
spring.datasource.url=jdbc:postgresql://pg2.sweb.ru:5432/hvatovacom_examp
spring.datasource.username=hvatovacom_examp
spring.datasource.password=Qwerty11

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect